### ISSUE TITLE
Value of the imitation loss weight balancing factor

### ISSUE THREAD

**Issue by bubbles1990** [twangnh/Distilling-Object-Detectors#1]
Thank you for the interesting paper and for sharing the code. I couldn't find the value of _λ_, the imitation loss weight balancing factor.
Thank you.

**Comment by twangnh** [comment]
Hi @bubbles1990 Thanks for the question, the balancing factor is at:
https://github.com/twangnh/Distilling-Object-Detectors/blob/48f0b6fd8dd838c0f032d34e9a452aa6d646cbaa/trainval_net_sup.py#L121

**Comment by bubbles1990** [comment]
Thank you for your quick response!
Is the default value `0.01` the one used in the paper?

**Comment by twangnh** [comment]
yes, 0.01 is used for vgg11-FRCNN, but for different case, the balancing factor should better be tuned.
